ck3g/homebugh

.travis.yml
db/migrate/20170625150708_create_budgets.rb
db/schema.rb

* Update Ruby version
* Allow to run builds against all branches
* Locks bundler version to 1.17.3
* Adds MySQL service to Travis
* Updates DB schema
Closes https://github.com/ck3g/homebugh/issues/21

Update Travis CI config

---

README.md
db/seeds.rb

Fixes https://github.com/ck3g/homebugh/issues/29

Add development instructions to README

---

.github/workflows/greetings.yml

More info here https://github.com/actions/first-interaction/issues/10#issuecomment-670968624

Fix greetings action

---

app/models/account.rb
app/models/aggregated_transaction.rb
app/models/application_record.rb
app/models/budget.rb
app/models/cash_flow.rb
app/models/category.rb
app/models/category_type.rb
app/models/currency.rb
app/models/transaction.rb
app/models/user.rb

- Introduce `ApplicationRecord` abstract model
- Inherit all the models from `ApplicationRecord`

Inherit all models from ApplicationRecord

---

app/models/account.rb
app/models/category.rb
app/models/recurring_payment.rb
app/models/user.rb
db/migrate/20200930183153_create_recurring_payments.rb
db/schema.rb
spec/factories/recurring_payments.rb
spec/models/account_spec.rb
spec/models/category_spec.rb
spec/models/recurring_payment_spec.rb
spec/models/user_spec.rb

Implements #61
- Creates `recurring_payments` table
- Creates `RecurringPayment` model
- Add validations and associations
- Ensures recurring payments deletes with a user data

Create recurring payment model

---

app/views/devise/passwords/new.html.haml

Fixes # .
Made the forgot password form wider :)

feat: make forgot password form wider #25

---

Gemfile
Gemfile.lock
app/assets/javascripts/transactions.js
app/assets/javascripts/transactions.js.coffee

Fixes https://github.com/ck3g/homebugh/issues/50
Removes usage of coffee-rails

Remove coffee-rails and rework coffeescript to js

---

app/controllers/users_controller.rb
app/views/users/delete.html.haml
config/locales/en.yml
config/routes.rb
spec/controllers/users_controller_spec.rb

Fixes https://github.com/ck3g/homebugh/issues/30
Adds a delete action for users

Add Users#delete action and specs

---

Gemfile
Gemfile.lock
config/application.rb
spec/factories/accounts.rb
spec/factories/aggregated_transactions.rb
spec/factories/budgets.rb
spec/factories/cash_flows.rb
spec/factories/categories.rb
spec/factories/currencies.rb
spec/factories/recurring_payments.rb
spec/factories/transactions.rb
spec/factories/users.rb
spec/rails_helper.rb
spec/support/login_macros.rb

Fixes https://github.com/ck3g/homebugh/issues/46
Change FactoryGirl for FactoryBot and upgrade to 4.8.2

Transition to factory bot

---

db/migrate/20200929021015_add_demo_user_to_users.rb
db/schema.rb

Fixes #34 
- Add demo_user column to users table

feat: add demo user column to users table

---

db/migrate/20201001090753_add_show_in_summary_to_accounts.rb
db/schema.rb

Fixes #57 
- Add show in summary to accounts table

feat: add show in summary to accounts table

---

app/views/devise/registrations/edit.html.haml
config/locales/en.yml
config/locales/ru.yml

Fixes #27 .
-Added some translations for User editing page

Add some translations for User editing page Issue 27

---

db/seeds.rb

Creates a demo user record from the seeds

Create demo user from seeds

---

Gemfile.lock
app/controllers/recurring_payments_controller.rb
app/decorators/recurring_payment_decorator.rb
app/models/ability.rb
app/models/recurring_payment.rb
app/views/recurring_payments/index.html.haml
config/locales/en.yml
config/routes.rb
spec/features/recurring_payments_list_spec.rb
spec/models/ability_spec.rb

Fixes https://github.com/ck3g/homebugh/issues/63
- Renders the list of a user's recurring payments on the page

Display list of recurring payments

---

README.md

Fixes #20  .
-Fixed link to Travis CL

Fixed link to Travis CL on README.md

---

app/controllers/recurring_payments_controller.rb
app/views/recurring_payments/index.html.haml
config/routes.rb
spec/features/recurring_payments/delete_recurring_payments_spec.rb

Fixes #66
- Provides ability to delete recurring payments

Allow to delete recurring payments

---

app/controllers/recurring_payments_controller.rb
app/helpers/application_helper.rb
app/views/recurring_payments/_form.html.haml
app/views/recurring_payments/index.html.haml
app/views/recurring_payments/new.html.haml
config/locales/en.yml
config/routes.rb
spec/features/recurring_payments/create_recurring_payment_spec.rb
spec/models/ability_spec.rb

Fixes #64
- Add "New recurring payment" page and allows to create new records

Allow to create recurring payments

---

app/controllers/recurring_payments_controller.rb
app/views/recurring_payments/edit.html.haml
app/views/recurring_payments/index.html.haml
config/locales/en.yml
config/routes.rb
spec/features/recurring_payments/edit_recurring_payment_spec.rb

Fixes https://github.com/ck3g/homebugh/issues/65

Update recurring payments

---

app/assets/stylesheets/application.css.scss
app/assets/stylesheets/transactions.css.scss
app/helpers/application_helper.rb
app/views/accounts/_form.html.haml
app/views/accounts/edit.html.haml
app/views/accounts/new.html.haml
app/views/budgets/_form.html.haml
app/views/budgets/edit.html.haml
app/views/budgets/index.html.haml
app/views/budgets/new.html.haml
app/views/cash_flows/_form.html.haml
app/views/cash_flows/new.html.haml
app/views/categories/_form.html.haml
app/views/categories/edit.html.haml
app/views/categories/new.html.haml
app/views/devise/registrations/edit.html.haml
app/views/recurring_payments/_form.html.haml
app/views/recurring_payments/edit.html.haml
app/views/recurring_payments/index.html.haml
app/views/recurring_payments/new.html.haml
app/views/shared/_top_navbar.html.haml
app/views/transactions/_form.html.haml
app/views/transactions/new.html.haml
app/views/users/delete.html.haml
config/locales/en.yml
config/locales/ru.yml

Adds a bunch of layout improvements: tweaks input sizes, add spacing between elements, reposition form titles, etc.

Tweak layout

---

app/helpers/application_helper.rb
app/models/recurring_payment.rb
app/views/recurring_payments/index.html.haml
config/locales/en.yml
config/locales/ru.yml
spec/models/recurring_payment_spec.rb

Fixes https://github.com/ck3g/homebugh/issues/88

Add translations for recurring payments

---

app/decorators/recurring_payment_decorator.rb
app/models/concerns/categorizable.rb
app/models/recurring_payment.rb
app/models/transaction.rb
app/views/recurring_payments/index.html.haml
spec/models/recurring_payment_spec.rb

Display category type icon for recurring payments

---

app/controllers/recurring_payments_controller.rb
app/helpers/application_helper.rb
app/views/recurring_payments/_form.html.haml
app/views/transactions/index.html.haml
spec/features/recurring_payments/create_recurring_payment_spec.rb

Allows to create a recurring payment from an existing transaction

Create a recurring payment from a transaction

---

app/views/accounts/_form.html.haml
spec/features/account_spec.rb

* Adds specs for "show in summary" checkbox
* Fixes checkbox layout

Add specs for show in summary

---

app/models/account.rb
app/views/layouts/_total_funds.html.haml

Fixes https://github.com/ck3g/homebugh/issues/60
- Based on https://github.com/ck3g/homebugh/issues/57 and https://github.com/ck3g/homebugh/issues/58, this PR attempts to display in the accounts summary only those accounts which show_in_summary is enabled.

Show accounts in the summary when show_in_summary is true

---

app/controllers/recurring_payments_controller.rb
app/models/recurring_payment.rb
app/views/recurring_payments/index.html.haml
config/locales/ru.yml
config/routes.rb
spec/factories/recurring_payments.rb
spec/features/recurring_payments/move_to_the_next_payment_date_spec.rb
spec/models/recurring_payment_spec.rb

Fixes https://github.com/ck3g/homebugh/issues/102
- Adds a button next to a recurring payment to move it to the next payment period

Add ability to move recurring payments to the next period

---

app/views/layouts/_total_funds.html.haml
lib/total_amount.rb
spec/factories/accounts.rb
spec/lib/total_amount_spec.rb

Don't display the total amount of deleted and hidden from summary accounts

Exclude deleted and hidden accounts from summary

---

README.md
docs/deploying_to_heroku.md

Move deploying to Heroku guide into docs

---

app/views/devise/sessions/new.html.haml

Fixes # .
- Fixed alignment of remember-me checkbox at /homebugh/app/assets/stylesheets/custom.css.scss
-
-

Fixed alignment of remember-me checkbox

---

app/models/auth_session.rb
db/migrate/20201101085144_create_auth_sessions.rb
db/schema.rb
spec/factories/auth_sessions.rb
spec/models/auth_session_spec.rb

Create a table to hold API sessions data

Add AuthSession model to hold API sessions data

---

config/initializers/devise.rb

Fixes https://github.com/ck3g/homebugh/issues/125

Remove pepper from devise config
